[package]
name = "cetkaik_full_state_transition"
version = "0.1.0"
authors = ["jekto_vatimeliju <jekto.vatimeliju@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cetkaik_core = "0.1.13"
cetkaik_yhuap_move_candidates = "0.1.0"
readonly = "0.2.0"
