[package]
authors = ["jekto_vatimeliju <jekto.vatimeliju@gmail.com>"]
edition = "2018"
name = "cetkaik_full_state_transition"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cetkaik_calculate_hand = "0.1.2"
cetkaik_core = "0.2.2"
cetkaik_yhuap_move_candidates = "0.1.3"
readonly = "0.2.0"
maplit = "1.0.2"